### ISSUE TITLE
"promise not returned" error in cap table

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#136]
in console:

```
[Home] *Proposals in swarmbot lovers*
1: duke
2: foo

*Actions:*
3: Create a proposal
4: Cap table
5: More commands

To take an action, simply enter the number or letter at the beginning of the line.

s> s 4
s>   app state: general#home +3s
[
    {
        "address": "mn9q6NQSbpeRaii7QULiohGG2wjMTmjJVK",
        "amount": 100000000
    }
]
Warning: a promise was created in a  handler but was not returned from it
  at /Users/harlan/cc-code/swarmbot/src/models/user.coffee:29:16
  at c (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:230:55)
  at /Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:46:642
  at Bb (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:43:165)
  at xb (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:22:216)
  at yb (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:21:1260)
  at Yh.g.Eb (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:206:287)
  at Kh.g.Gd (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:193:251)
  at yh.Gd (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:183:364)
  at qh.xg (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:181:281)
  at th (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:175:464)
  at [object Object].ua.onmessage (/Users/harlan/cc-code/swarmbot/node_modules/firebase/lib/firebase-node.js:174:321)
  at [object Object].EventTarget.dispatchEvent (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
  at [object Object].instance._receiveMessage (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
  at [object Object].<anonymous> (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
  at [object Object].emit (events.js:117:20)
  at [object Object].<anonymous> (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
  at pipe (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
  at [object Object].Pipeline._loop (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
  at [object Object].Pipeline.processIncomingMessage (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
  at [object Object].instance.processIncomingMessage (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
  at [object Object].instance._emitMessage (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
  at [object Object].instance._emitFrame (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
  at [object Object].instance.parse (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
  at [object Object].instance.parse (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
  at [object Object].IO.write (/Users/harlan/cc-code/swarmbot/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
  at write (_stream_readable.js:602:24)
  at flow (_stream_readable.js:611:7)
  at CleartextStream.pipeOnReadable (_stream_readable.js:643:5)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:448:13)

```

**Comment by harlantwood** [comment]
@dukedorje this is new since `kebab` refactoring
