### ISSUE TITLE
Sometimes crash when logging in

### ISSUE THREAD

**Issue by harlantwood** [citizencode/swarmbot#403]
from prod logs:

2016-02-25T20:12:34.890247+00:00 app[web.1]: ActiveRecord::RecordInvalid (Validation failed: Name can't be blank):
2016-02-25T20:12:34.890248+00:00 app[web.1]:   app/models/authentication.rb:28:in `find_or_create_from_auth_hash!'
2016-02-25T20:12:34.890265+00:00 app[web.1]:   app/controllers/sessions_controller.rb:15:in `create'

**Comment by harlantwood** [comment]
even users without a name in slack should be able to log in now
